services:

    form.type.usergroup:
        class: Flower\UserBundle\Form\Type\UserGroupType
        arguments: ["@flower.security.roles"]
        tags:
            - { name: form.type, alias: event_type }

    form.type.securitygroup:
        class: Flower\UserBundle\Form\Type\SecurityGroupType
        tags:
            - { name: form.type, alias: securitygroup_type }


    symfony.form.type.tree:
           class: Yavin\Symfony\Form\Type\TreeType
           arguments: [ "@property_accessor" ]
           tags:
               - { name: form.type, alias: y_tree }

    symfony.form.type_guesser.tree:
       class: Yavin\Symfony\Form\Type\TreeTypeGuesser
       arguments: [ "@doctrine" ]
       tags:
           - { name: form.type_guesser }


    user.service.orgposition:
            class: Flower\UserBundle\Service\OrgPositionService
            arguments: ['@service_container']

    user.service.securitygroup:
            class: Flower\UserBundle\Service\SecurityGroupService
            arguments: ['@service_container']