<?php

namespace Flower\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrgPosition
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgPositionRepository extends EntityRepository
{

}
