<?php

namespace Flower\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrgPosition
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityGroupRepository extends EntityRepository
{
    public function getOneByAssignee($assigneeId){
        $qb = $this->createQueryBuilder("sg");
        $qb->join("sg.assignee", "a");
        $qb->where("a.id = :assignee_id")->setParameter("assignee_id", $assigneeId);
        $qb->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
