<?php

namespace Flower\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationRepository extends EntityRepository
{
    public function getUnreadsCount($userId){

        $qb = $this->createQueryBuilder("n");

        $qb->select("COUNT(n)");
        $qb->where("n.user = :user_id")->setParameter("user_id", $userId);
        $qb->andWhere("n.viewed = :read")->setParameter("read", false);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
